name: Run Python tests

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - uses: snok/install-poetry@v1
      with:
        version: 2.1.2
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
    - name: Install Poetry dependencies
      run: poetry install --no-interaction --no-root --with dev
      shell: bash
    - name: Collect statics assets
      run: poetry run python manage.py collectstatic
      shell: bash
    - name: Run Python tests
      run: poetry run python manage.py test
      shell: bash
