name: Run Python tests

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Start Docker containers
      run: docker compose up --detach --wait --wait-timeout 300 || docker compose logs app
      shell: bash
    - name: Run check in the app Docker container
      run: docker compose exec app poetry run python /app/manage.py check
      shell: bash
    - name: Run tests in the dev Docker container
      run: docker compose exec dev poetry run python /app/manage.py test
      shell: bash
    - name: Check for missing migrations
      run: docker compose exec app poetry run python /app/manage.py makemigrations --check --noinput
      shell: bash
