name: Pull request

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Run tests
        uses: ./.github/actions/node-tests

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Run tests
        uses: ./.github/actions/python-tests

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Run tests
        uses: ./.github/actions/check-formatting
