name: Pull request

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run tests
        uses: ./.github/actions/node-tests

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run tests
        uses: ./.github/actions/python-tests

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run tests
        uses: ./.github/actions/check-formatting
